### ISSUE TITLE
[QUESTION] Is it possible to self-recommend our package for curated?

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/vpm-listing-curated#22]
Is it possible to self-recommend our package for curated repository?
If we can, could you tell us how?

I'm developing [AAO] (AAO: Avatar Optimizer), an tool to optimize avatar automatically.
I sometimes wonder if this can be a curated package but it looks there are no public documentation about get package curated.

Since [NDMF], one of AAO's dependencies, is young project so I think it's not time yet but when time comes, I want to self-recommend AAO and dependencies for curated package.

Thank you.

[AAO]: https://vpm.anatawa12.com/avatar-optimizer/en/
[NDMF]: https://ndmf.nadena.dev/

**Comment by BluWizard10** [comment]
Shocking that nobody replied to this message yet!

But if I understand this correctly (and this is from my personal observations, I am NOT a VRC Staff member whatsoever), I think you can just simply make a fork and write in your Package as an entry in this listing. Then of course, make a Pull Request.

Make a PR proposing you wish to see something like AAO added a Curated Package using the proper VPM Listing format, then cross your fingers and hope Momo agrees with adding it. As I've observed from previous PRs in here, it will need to pass some sort of Security Check. If Momo finds anything in violation, they will tell you and recommend you make the necessary changes.

If it passes all their Security Checks, Momo will approve it and leave a note for you before it is merged.

With that being said, best of luck to you if you do decide to become a Curated Package!

**Comment by anatawa12** [comment]
According to https://github.com/vrchat-community/vpm-listing-curated/pull/43#issuecomment-2221068252, VRChat doesn't accept bew curated packages.


I’m going to create PR that adds this info and close this issue with the pr
